---
- hosts: all
  become: yes

  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Install Apache.
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - apache2
        - apache2-doc

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: Create the directory structure for site.
      file: path=/var/www/{{ item.0 }}/{{ item.1 }}/{{ item.2 }} owner=root group=root mode=0755 recurse=yes state=directory
      with_nested:
      - ['html']
      - ['d.ditelkin.com', 'd1.ditelkin.com', 'd2.ditelkin.com', 'd3.ditelkin.com']
      - ['public_html', 'logs']

    - name: Copy demo pages for virtual host.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - { src: "index.html", dest: "/var/www/html/d.ditelkin.com/public_html/index.html" }
        - { src: "index1.html", dest: "/var/www/html/d1.ditelkin.com/public_html/index.html" }
        - { src: "index2.html", dest: "/var/www/html/d2.ditelkin.com/public_html/index.html" }
        - { src: "index3.php", dest: "/var/www/html/d3.ditelkin.com/public_html/index.php" }
      notify:
        - restart apache2

    - name: Copy Virtual Host file.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - { src: 'ditelkin.conf', dest: '/etc/apache2/sites-available/ditelkin.conf' }
        - { src: 'ditelkin1.conf', dest: '/etc/apache2/sites-available/ditelkin1.conf' }
        - { src: 'ditelkin2.conf', dest: '/etc/apache2/sites-available/ditelkin2.conf' }
        - { src: 'ditelkin3.conf', dest: '/etc/apache2/sites-available/ditelkin3.conf' }
      notify:
        - restart apache2

    - name: a2dissite default site
      command: a2dissite {{ item }}
      with_items:
        - 000-default.conf

    - name: a2ensite our sites
      command: a2ensite {{ item }}
      args:
        creates: /etc/apache2/sites-enabled/{{ item }}
      with_items:
        - ditelkin.conf
        - ditelkin1.conf
        - ditelkin2.conf
        - ditelkin3.conf
      notify:
        - restart apache2

    - name: Start the service at boot
      service: name={{ item }} state=started enabled=yes
      with_items:
        - apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted