---
- hosts: all
  become: yes

  tasks:
    - name: Install Apache.
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: Copy demo pages for virtual host.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: "index.html"
          dest: "/var/www/html/index.html"

    - name: Make sure Apache is started and enabled on boot.
      service: name=apache2 state=started enabled=yes

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted