---
- hosts: all
  become: yes

  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Install Apache.
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted