---
- hosts: all
  become: yes
  vars:
    MySQL_root_pass: Materobi1*

  tasks:
    - name: Install MySQL.
      apt: name={{ item }} state=latest force=yes update_cache=yes cache_valid_time=3600
      when: ansible_os_family == 'Debian'
      with_items:
        - mysql-server
        - mysql-client
        - python-mysqldb

    - name: update mysql root password for all root accounts
      mysql_user: user="root" password="{{ MySQL_root_pass }}" host="{{ item }}" login_password="{{ MySQL_root_pass }}" login_user=root check_implicit_admin=yes priv="*.*:ALL,GRANT"
      with_items:
         - 127.0.0.1
         - localhost
         - ::1

    - name: Deletes anonymous MySQL server user for localhost
      mysql_user: user="" state="absent" login_password="{{ MySQL_root_pass }}" login_user=root

    - name: Secures the MySQL root user
      mysql_user: user="root" password="{{ MySQL_root_pass }}" host="{{ item }}" login_password="{{ MySQL_root_pass }}" login_user=root
      with_items:
        - 127.0.0.1
        - localhost
        - ::1

    - name: Removes the MySQL test database
      mysql_db: db=test state=absent login_password="{{ MySQL_root_pass }}" login_user=root

    - name: Start the service at boot
      service: name={{ item }} state=started enabled=yes
      with_items:
        - mysql