---
- hosts: all
  become: yes

  tasks:
    - name: Install PHPMYADMIN.
      apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
      when: ansible_os_family == 'Debian'
      with_items:
        - phpmyadmin
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted